INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_CATEGORY) VALUES(1,'ABC',23,'X');
INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_CATEGORY) VALUES(2,'BBC',50,'Y');